function [cur_ctl] = policy_improvement(config, cur_state, cur_ctl, J2L_mat,...
    theta_max, coeff, unit_ball_sample, non_zero_count)
% 根据控制变量受限与不受限情况，根据实际输出将策略提升步骤分为约束优化与
% 无约束优化两种情况
opts = optimoptions("fmincon", 'Algorithm', "sqp", 'MaxIterations', 500,'MaxFunctionEvaluations',500);

lst_ctl = cur_ctl;
%% 无约束优化情况
if config.cst_flag == 0
    % costate = zeros(size(cur_state));
    for i=1:size(cur_state, 2)

    cur_ctl(1:2*config.ctl_dim, i) = fmincon(@(ctl) tgt_fun_po_im(coeff(:...
        , 1), cur_state(:, i), config, J2L_mat, theta_max(:, i), [ctl;...
        cur_ctl(2*config.ctl_dim+1:end, i)], lst_ctl, "V_T", unit_ball_sample, ...
        non_zero_count), cur_ctl(1:2*config.ctl_dim, i), [],[],[],[],[],[],[],...
        opts);

    cur_ctl(2*config.ctl_dim+1:end, i) = fmincon(@(ctl) tgt_fun_po_im(...
        coeff(:, 2), cur_state(:, i), config, J2L_mat, theta_max(:, i),...
        [cur_ctl(1:2*config.ctl_dim, i); ctl], lst_ctl, "V_R", unit_ball_sample, ...
        non_zero_count), cur_ctl(2*config.ctl_dim+1:end, i), [],[],[],[],[],[],[],...
        opts);
    end
%% 约束优化情况
else
    for i=1:size(cur_state, 2)

    cur_ctl(1:2*config.ctl_dim, i) = fmincon(@(ctl) tgt_fun_po_im(coeff(:...
        , 1), cur_state(:, i), config, J2L_mat, theta_max(:, i), ...
        [ctl;cur_ctl(2*config.ctl_dim+1:end, i)], lst_ctl, "V_T", unit_ball_sample, ...
        non_zero_count), cur_ctl(1:2*config.ctl_dim, i), [],[],[],[],[],[],...
        @(cur_ctl) po_im_cst(config, cur_ctl, "V_T"), opts);

    cur_ctl(2*config.ctl_dim+1:end, i) = fmincon(@(ctl) tgt_fun_po_im(...
        coeff(:, 2), cur_state(:, i), config, J2L_mat, theta_max(:, i),...
        [cur_ctl(1:2*config.ctl_dim, i);ctl], lst_ctl, "V_R", unit_ball_sample, ...
        non_zero_count), cur_ctl(2*config.ctl_dim+1:end, i), [],[],[],[],[],[],...
        @(cur_ctl) po_im_cst(config, cur_ctl, "V_R"), opts);
    end
end

end