function [cur_ctl] = policy_improvement(config, cur_state, his_obs, J2L_mat,...
    theta_max, coeff)
% 根据控制变量受限与不受限情况，根据实际输出将策略提升步骤分为约束优化与
% 无约束优化两种情况
opts = optimoptions('fmincon', 'Algorithm', 'sqp');
cur_ctl = zeros([(2+config.num_rec_sat)*config.ctl_dim, size(cur_state, 2)]);
%% 无约束优化情况
if config.cst_flag == 0
    % costate = zeros(size(cur_state));
    for i=1:size(cur_state, 2)

    cur_ctl(1:2*config.ctl_dim, i) = fmincon(@(ctl) tgt_fun_po_im(coeff(:...
        , 1), cur_state(:, i), config, his_obs, J2L_mat, theta_max(:, i), ...
        [ctl;cur_ctl(2*config.ctl_dim+1:end, i)], "V_T"), cur_ctl(1:2*...
        config.ctl_dim, i), [],[],[],[],[],[],[], opts);

    cur_ctl(2*config.ctl_dim+1:end, i) = fmincon(@(ctl) tgt_fun_po_im(...
        coeff(:, 2), cur_state(:, i), config, his_obs, J2L_mat, theta_max(:, i),...
        [cur_ctl(1:2*config.ctl_dim, i);ctl], "V_R"), cur_ctl(2*...
        config.ctl_dim+1:end, i), [],[],[],[],[],[],[], opts);
    % cur_ctl(1:config.ctl_dim, i) = u_costate_att(config, costate(1:...
    %     config.att_dim, i));
    % cur_ctl(config.ctl_dim+1:2*config.ctl_dim, i) = u_costate_orb_tgt...
    %     (config, costate(config.att_dim+1:end, i));
    % for j=1:config.num_rec_sat
    %     cur_ctl((j+1)*config.ctl_dim+1:(j+2)*config.ctl_dim, i) = ...
    %         u_costate_orb_rec(config, costate(config.att_dim+((j-1)*...
    %         config.orb_dim+1:j*config.orb_dim), i));
    % end
    end
%% 约束优化情况
else
    for i=1:size(cur_state, 2)

    cur_ctl(1:2*config.ctl_dim, i) = fmincon(@(ctl) tgt_fun_po_im(coeff(:...
        , 1), cur_state(:, i), config, his_obs, J2L_mat, theta_max(:, i), ...
        [ctl;cur_ctl(2*config.ctl_dim+1:end, i)], "V_T"), cur_ctl(1:2*...
        config.ctl_dim, i), [],[],[],[],[],[], @(cur_ctl) po_im_cst(...
        config, cur_ctl, "V_T"), opts);

    cur_ctl(2*config.ctl_dim+1:end, i) = fmincon(@(ctl) tgt_fun_po_im(...
        coeff(:, 2), cur_state(:, i), config, his_obs, J2L_mat, theta_max(:, i),...
        [cur_ctl(1:2*config.ctl_dim, i);ctl], "V_R"), cur_ctl(2*...
        config.ctl_dim+1:end, i), [],[],[],[],[],[], @(cur_ctl) po_im_cst(...
        config, cur_ctl, "V_R"), opts);
    end
end

end